version: "3"

services:
  sonarqube:
    image: sonarqube:lts-community
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_logs:/opt/sonarqube/logs
    ports:
      - "9000:9000"
    networks:
      - sonarnet

  sonarqube_execution:
    depends_on:
      - sonarqube
    image: sonarsource/sonar-scanner-cli
    volumes:
      - ./:/app
    networks:
      - sonarnet
    environment:
      - SONAR_HOST_URL=http://sonarqube:9000
      - SONAR_LOGIN=admin
      - SONAR_PASSWORD=admin
      - SONAR_PROJECTKEY=sonarscanner
    restart: on-failure

networks:
  sonarnet:

volumes:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_logs:
