version: "3"

services:
  sonarqube:
    image: sonarqube:lts-community
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_logs:/opt/sonarqube/logs
    ports:
      - "9000:9000"
    networks:
      - sonarnet

  maven_sonarscanner:
    container_name: maven_sonarscanner
    depends_on:
      - sonarqube
    build:
      context: .
      dockerfile: Dockerfile
      args:
        JDK_VERSION: ${JDK_VERSION}
    volumes:
      - ${PROJECT_PATH}:/${PROJECT_PATH}
    working_dir: /${PROJECT_PATH}
    networks:
      - sonarnet
    restart: on-failure
    entrypoint: /entrypoint.sh

networks:
  sonarnet:

volumes:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_logs:
