---
name: microflow-execution

on:
  workflow_dispatch:
    inputs:
      autor_proyecto:
        description: 'Autor/proyecto a analizar'
        required: true
        default: ''

jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout input project
        uses: actions/checkout@v3
        with:
          repository: ${{ github.event.inputs.autor_proyecto }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Copy project
        run: |
          mkdir /home/runner/microflow && cp -r -p . /home/runner/microflow/

      - name: Checkout microflow project
        uses: actions/checkout@v3

      - name: Docker compose up
        run: PROJECT_PATH=/home/runner/microflow docker-compose up -d

      - name: Retrieve scanner results
        run: |
          while [[ $(docker container ps -q -f status=exited) == "" ]]; do
            true
          done
        
      - name: setup python
        uses: actions/setup-python@v3
        with:
          python-version: 3.8
          cache: 'pip'

      - name: Install python dependencies
        run: pip install -r maven_sonarscanner/requirements.txt

      - name: Get analysis results via SonarQube API
        run: |
          python maven_sonarscanner/generate-results.py
          cp results_markdown.md /home/runner/results_markdown.md
          cp charts.html /home/runner/charts.html

      - name: Checkout to ghpages branch
        uses: actions/checkout@v3
        with:
          ref: ghpages

      - name: Update github page
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"

          mv -i /home/runner/results_markdown.md index.md
          mv -i /home/runner/charts.html _includes/charts.html
          git add index.md _includes/charts.html
          git commit -m "Updated gh page with ${{ github.event.inputs.autor_proyecto }} analysis"
          git push

      - name: Docker compose down
        run: docker-compose down
