---
name: microflow-execution

on:
  workflow_dispatch:
    inputs:
      autor_proyecto:
        description: 'Autor/proyecto a analizar'
        required: true
        default: ''

jobs:
  retrieve-project:
    id: retrieve-scanner
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout input project
        uses: actions/checkout@v3
        with:
          repository: ${{ github.event.inputs.autor_proyecto }}
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Cache scanner results
        uses: actions/cache@v2
        env:
          cache-name: cache-project
        with:
          path: .
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('pom.xml') }}

  sonarqube-scanner:
    runs-on: ubuntu-20.04
    needs: retrieve-scanner
    steps:
      - name: Checkout microflow project
        uses: actions/checkout@v3

      - name: Cache project
        id: cache-project
        uses: actions/cache@v2
        with:
          path: .
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Docker compose up
        run: PROJECT_PATH=. docker-compose up -d

      - name: Retrieve scanner results
        run: |
          while [[ $(docker container ps -q -f status=exited) == "" ]]; do
            true
          done
        
      - name: setup python
        uses: actions/setup-python@v3
        with:
          python-version: 3.8
          cache: 'pip'

      - name: Install python dependencies
        run: pip install -r maven_sonarscanner/requirements.txt

      - name: Get analysis results via SonarQube API
        run: |
          python maven_sonarscanner/generate-results.py
          mkdir scanner_results
          mv results_markdown.md scanner_results/
          mv charts.html scanner_results/

      - name: Cache scanner results
        uses: actions/cache@v2
        env:
          cache-name: cache-scanner
        with:
          path: scanner_results
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('charts.html') }}

      - name: Docker compose down
        run: docker-compose down -v

  checkstyle-spotbugs:
    needs: retrieve-scanner
    runs-on: ubuntu-20.04
    steps:

      - name: Checkout microflow project
        uses: actions/checkout@v3

      - name: Cache project
        id: cache-project
        uses: actions/cache@v2
        with:
          path: .
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Checkstyle execution and result publishing
        run: |
          docker run maven:3.8.5-jdk-8 mvn checkstyle:checkstyle-aggregate
          mkdir checkstyle_results
          mv -f ./target/site/checkstyle-aggregate.html checkstyle_results/

      - name: Cache scanner results
        uses: actions/cache@v2
        env:
          cache-name: cache-checkstyle
        with:
          path: checkstyle_results
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('./target/site/checkstyle-aggregate.html') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

  web-update:
    runs-on: ubuntu-20.04
    needs: [sonarqube-scanner, checkstyle-spotbugs]
    steps:
      - name: Checkout to ghpages branch
        uses: actions/checkout@v3
        with:
          ref: ghpages

      - name: Cache results Sonar scanner
        id: cache-results-scanner
        uses: actions/cache@v2
        with:
          path: scanner_results
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('charts.html') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Cache results checkstyle
        id: cache-results-checkstyle
        uses: actions/cache@v2
        with:
          path: checkstyle_results
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('./target/site/checkstyle-aggregate.html') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Update github page
        continue-on-error: true
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"

          mv -f scanner_results/results_markdown.md index.md
          mv -f scanner_results/charts.html _includes/charts.html
          mv -f checkstyle_results/checkstyle/target/site/checkstyle-aggregate.html checkstyle-aggregate.html

          git add index.md _includes/charts.html checkstyle-aggregate.html
          git commit -m "Updated gh page with ${{ github.event.inputs.autor_proyecto }} analysis"

          git push
