---
name: microflow-execution

on:
  workflow_dispatch:
    inputs:
      autor_proyecto:
        description: 'Autor/proyecto a analizar'
        required: true
        default: ''

jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout input project
        uses: actions/checkout@v3
        with:
          repository: ${{ github.event.inputs.autor_proyecto }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Copy project
        run: |
          mkdir /home/runner/ci-agents && cp -p . /home/runner/ci-agents/

      - name: Checkout microflow project
        uses: actions/checkout@v3

      - name: Build the stack
        run: docker-compose up -d
