---
name: secrets-detect

on:
  pull_request:

jobs:
  detect-secrets:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3
    - name: detect-secrets
      uses: reviewdog/action-detect-secrets@0.8.1
      with:
        github_token: ${{ secrets.github_token }}
        reporter: github-pr-review
        filter_mode: added
        fail_on_error: true
