---
name: yamllint-verify

on:
  pull-request:

jobs:
  check-changes-in-paths:
    name: Check for changes in corresponding paths
    runs-on: ubuntu-20.04
    outputs:
      yaml: ${{ steps.changes.outputs.yaml }}
      yaml-files: ${{ steps.changes.outputs.yaml_files }}
      markdown: ${{ steps.changes.outputs.markdown }}
      markdown-files: ${{ steps.changes.outputs.markdown_files }}
      workflows: ${{ steps.changes.outputs.workflows }}
      workflows-files: ${{ steps.changes.outputs.workflows_files }}
    steps:
      - name: Check for changed files in specific paths
        id: changes
        uses: dorny/paths-filter@v2.10.2
        with:
          list-files: shell
          filters: |
            yaml:
              - added|modified: '**.yml'
              - added|modified: '**.yaml'
            workflows:
              - added|modified: '.github/workflows/*.yml'
              - added|modified: '.github/workflows/*.yaml'
            python:
              - added|modified: '**.py'
            sh:
              - added|modified: '**.sh'
            dockerfile:
              - added|modified: 'Dockerfile'
  yaml-lint:
    name: YAML Lint
    needs: check-changes-in-paths
    if: needs.check-changes-in-paths.outputs.yaml == 'true'
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: YAML Lint
        run: yamllint -c .github/.yaml-lint.yml ${{ needs.check-changes-in-paths.outputs.yaml-files }}
  action-lint:
    name: Action Lint
    needs: check-changes-in-paths
    if: needs.check-changes-in-paths.outputs.workflows == 'true'
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Install pyflakes
        run: |
            pip install --upgrade pyflakes
      - name: Download actionlint
        id: get_actionlint
        run: bash <(curl https://raw.githubusercontent.com/rhysd/actionlint/e4caae93a1bc24ab2e349236b6b389900e5a7914/scripts/download-actionlint.bash) 1.6.13
      - name: Check changed workflow files
        run: |
            ${{ steps.get_actionlint.outputs.executable }} ${{ needs.check-changes-in-paths.outputs.workflows-files }}
  py-lint:
    name: Python Lint
    needs: check-changes-in-paths
    if: needs.check-changes-in-paths.outputs.python == 'true'
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pylint
      - name: Analysing the code with pylint
        run: |
          pylint ${{ needs.check-changes-in-paths.outputs.python-files }}
  shellcheck:
    name: Shellcheck
    needs: check-changes-in-paths
    if: needs.check-changes-in-paths.outputs.sh == 'true'
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Install shellcheck
        run: sudo apt install shellcheck
      - name: Run shellcheck on changed .py files
        run: |
          shellcheck --color=always --format=tty --severity=error ${{ needs.check-changes-in-paths.outputs.sh-files }}
      - name: Run shellcheck to provide additional information without failing
        continue-on-error: true
        run: |
          shellcheck --color=always --format=tty --severity=info ${{ needs.check-changes-in-paths.outputs.sh-files }}
  dockerfile-lint:
    name: Shellcheck
    needs: check-changes-in-paths
    if: needs.check-changes-in-paths.outputs.dockerfile == 'true'
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: lint
        uses: luke142367/Docker-Lint-Action@v1.1.1
        with:
          target: ${{ needs.check-changes-in-paths.outputs.dockerfile-files }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
